import { Finish } from "./types";

// Real Basebeton Originale colours from the official sample card
export const FINISHES: Finish[] = [
  {
    id: "dutch-grey",
    name: "Dutch Grey",
    rgb: [178, 175, 172],
    hex: "#B2AFAC",
    description: "10-1 · Basebeton Originale",
    popular: true,
  },
  {
    id: "wheat",
    name: "Wheat",
    rgb: [222, 210, 199],
    hex: "#DED2C7",
    description: "10-18 · Basebeton Originale",
    popular: true,
  },
  {
    id: "buff",
    name: "Buff",
    rgb: [189, 176, 168],
    hex: "#BDB0A8",
    description: "10-17 · Basebeton Originale",
    popular: false,
  },
  {
    id: "daw",
    name: "Daw",
    rgb: [236, 216, 173],
    hex: "#ECD8AD",
    description: "10-19 · Basebeton Originale",
    popular: false,
  },
  {
    id: "cord",
    name: "Cord",
    rgb: [228, 206, 172],
    hex: "#E4CEAC",
    description: "10-22 · Basebeton Originale",
    popular: false,
  },
  {
    id: "clay",
    name: "Clay",
    rgb: [172, 160, 152],
    hex: "#ACA098",
    description: "10-14 · Basebeton Originale",
    popular: true,
  },
  {
    id: "mud",
    name: "Mud",
    rgb: [121, 118, 114],
    hex: "#797672",
    description: "10-8 · Basebeton Originale",
    popular: false,
  },
  {
    id: "persian",
    name: "Persian",
    rgb: [99, 96, 92],
    hex: "#63605C",
    description: "10-9 · Basebeton Originale",
    popular: false,
  },
  {
    id: "pitch-black",
    name: "Pitch Black",
    rgb: [97, 97, 97],
    hex: "#616161",
    description: "10-10 · Basebeton Originale",
    popular: true,
  },
  {
    id: "mocca",
    name: "Mocca",
    rgb: [158, 137, 125],
    hex: "#9E897D",
    description: "10-23 · Basebeton Originale",
    popular: false,
  },
  {
    id: "pebble",
    name: "Pebble",
    rgb: [141, 138, 133],
    hex: "#8D8A85",
    description: "10-4 · Basebeton Originale",
    popular: true,
  },
  {
    id: "cord-warm",
    name: "Past Yellow",
    rgb: [210, 195, 172],
    hex: "#D2C3AC",
    description: "10-24 · Basebeton Originale",
    popular: false,
  },
];
